### ISSUE TITLE
Which part of http://aima.cs.berkeley.edu/3rd-ed/ is refered?

### ISSUE THREAD

**Issue by happy15** [cyrilou242/ftcc#1]
Hi there, glad to see your experiment and it's really fun to read.

You mentioned in README that `the ideas has been known for ages` and referred to http://aima.cs.berkeley.edu/3rd-ed/. 

Just wondering which part of the book is referred?

Thanks.

**Comment by cyrilou242** [comment]
Hey thanks!

There is a data compression part in the chapter Natural Language Processing, 2.1: "Classification by data compression".

(at least on my AIMA boook, 3rd edition, international edition).
